-- Database (DDL)
CREATE DATABASE IF NOT EXISTS TweetCount;
USE TweetCount;

-- Tabel (DDL)
CREATE TABLE Category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(15) NOT NULL
);

CREATE TABLE Tweet (
    id INT AUTO_INCREMENT PRIMARY KEY,
    likes INT,
    content VARCHAR(150) NOT NULL,
    username VARCHAR(50) NOT NULL,
    category_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES Category(id)
);

-- User (DCL)
USE mysql;

CREATE USER IF NOT EXISTS 'public'@'localhost'
IDENTIFIED BY '';

GRANT SELECT
ON TweetCount.*
TO 'public'@'localhost';

USE TweetCount;

-- Trigger
DELIMITER $$

CREATE TRIGGER OnDeleteCategory
BEFORE DELETE ON Category
FOR EACH ROW
BEGIN
    DELETE FROM Tweet
    WHERE category_id = OLD.id;
END$$

DELIMITER ;

-- Insert (DML)
INSERT INTO Category(name) VALUES ('Pro'), ('Netral'), ('Kontra');

INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (3, 'Setiap genre dakwah saya pikir baik. Ada Gus Iqdam Gus Muwafiq Gus Miftah Gus Baha Gus Ali Gondrong Kyai Anwar Zahid Habib Sech Ustadz Safiq dan Riza Basalamah UAH UAS dll. Yg penting tujuannya utk mendidik umat islam. Jangan saling mencela.', 'ToufikImtikhan2', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'meninggalkan rumah membuat saya paham kenapa gus miftah dakwah ditempat yg ktanya gk baik itu...', 'briyan_arfi', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Semoga dakwah Gus Miftah semakin memberi manfaat untuk umat Islam. #KembaliCeramah', 'bayu_banggarr', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Semoga Gus Miftah terus diberi kekuatan dalam menyampaikan dakwah. #KembaliCeramah', 'zahra_safitri12', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, 'Kembalinya Gus Miftah adalah angin segar untuk dunia dakwah yang penuh dengan kedamaian. #KembaliCeramah', 'nadia_nisa0', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Semoga Gus Miftah terus diberi kekuatan untuk menyampaikan dakwah dengan penuh hikmah. #KembaliCeramah', 'sanny_mthri', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kehadiran Gus Miftah kembali memberi semangat baru dalam dakwah yang penuh kebijaksanaan. #KembaliCeramah', 'fadli_samudra2', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kembali ceramah Gus Miftah Kami sangat beruntung bisa menjadi bagian dari perjalanan dakwah beliau. #KembaliCeramah', 'kurni_maulana', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kembalinya Gus Miftah ke panggung dakwah selalu jadi momen yang ditunggu-tunggu. Banyak banget ilmu yang bisa diambil #KembaliCeramah', 'sapiul_ebell', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@03__nakula Jamaahnya kenal dengan Gus miftah dan paham dengan candaan Gus Muliftah seperti kita dengan sahabat atau teman sepermainan pasti hal bercanda saling ledek kata Atau menghina udh biasa dlm pergaulan dan pertemanan seperti itulah dakwah Gus miftah jamaah di jdikan teman dan sahbt', 'MuhammadNa29081', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@narkosun Insyaallah Allah klo ada rezeki saya undang Gus Miftah 200jt untuk seorang kyai bagiku itu gk mahal karena ada d jalan Allah 100jt untuk penyanyi bagiku mahal sehali Mantap Gus terus berikan ilmumu jgn hirokan setan setan yg coba ngalangin jalan dakwah mu Gus', 'Erde122361051', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Gus Miftah ngatain orang GOBLOK di bilang itu gak kasar dakwahnya memang begitu setiap kyai punya cara sendiri dalam berdakwah.', 'GanjaOto', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Piyusaja2 Belajar islam tu kayak sekolah lah.. Bagus banget kalau orang yg jauh sama Islam bisa kenal islam lewat Gus Miftah lalu naik lagi belajar ke habib jafar udah gitu harus naik kelas lagi belajar ke ust Adi Hidayat dst..', 'gitsunine', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'tempodotco minta maaf secara publik udah mundur Krn tdk tidak sanggup mengemban jabatan udah anda tidak hanya sebagai pendakwah anda juga seorang ksatria Gus bangsa ini musti bnyk belajar dri anda terutama pejabat publiknya. rispke Gus Miftah.. 5 jempol untuk anda', 'GemsBsc45364', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (3, '@wahyu_djanti88 @AYB_id @tonichan157 tergantung gimana penyampaiannya sih.. aku suka habib ja''far suka gus miftah.. tapi juga suka ust. hanan attaki ust. khalid bassalamah alm. syech ali jaber.. kalo dakwah disampaikan dengan adem pasti banyak yg mau mendengerkan', 'ToufikImtikhan2', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (4, '@ARSIPAJA Sy bkn jemaah beliau Tp bbrpa x suka nonton kajian beliau di YT Ga ada yg aneh Ga ada ujaran kebencian Justru suara ust. Syafiq lembut bgt Sy yg msh begajulan aja bs nrma isi dakwah beliau Sehat2 ya ustd @ustadzsyafiq Mgkn bg mrka ustd yg keren itu cmn gus miftah', 'pecozier', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Semoga dakwah Gus Miftah semakin memberi manfaat untuk umat Islam. #KembaliCeramah', 'bayu_banggarr', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Semoga Gus Miftah terus diberi kekuatan dalam menyampaikan dakwah. #KembaliCeramah', 'zahra_safitri12', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@OmletAtlantis @ccmlyneu @Eviicak2 @_172jt w tau soal itu bang. w bahkan tau Baginda Nabi Muhammad Saw cinta banget sama umatnya. goblokin=Gus Miftah pdhl banyak orang mualaf karena ceramah beliau. jika abangnya lebih berilmu coba jelasin kenapa harus saling menjatuhkan sesama umat muslim?', 's_assidiq', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, 'Kembalinya Gus Miftah adalah angin segar untuk dunia dakwah yang penuh dengan kedamaian. #KembaliCeramah', 'nadia_nisa0', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Semoga Gus Miftah terus diberi kekuatan untuk menyampaikan dakwah dengan penuh hikmah. #KembaliCeramah', 'sanny_mthri', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@Gus_Arifin Model pendakwah gini coba sekali2 dakwah di kawasan Diskotik/Jalanan semacamnya apakah bisa ? Yg ada merasa paling Suci. Miftah itu bukan orang suci sama2 bajingan kaya kita-kita bahkan Miftah mendapatkan julukan Presiden Para Pendosa itu bukan karena tanpa sebab', 'ohyaokesiapwkwk', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kehadiran Gus Miftah kembali memberi semangat baru dalam dakwah yang penuh kebijaksanaan. #KembaliCeramah', 'fadli_samudra2', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kembali ceramah Gus Miftah Kami sangat beruntung bisa menjadi bagian dari perjalanan dakwah beliau. #KembaliCeramah', 'kurni_maulana', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (16, 'Mulai Aktif Dakwah Lagi Gus Miftah Merasa Ksatria Sejati: Menyerang Tanpa Bawa Pasukan https://t.co/Kf2mZ9Y8h3', 'OposisiCerdas', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kembalinya Gus Miftah ke panggung dakwah selalu jadi momen yang ditunggu-tunggu. Banyak banget ilmu yang bisa diambil #KembaliCeramah', 'sapiul_ebell', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (36, 'Kembalinya Gus Miftah Membawa Angin Segar untuk Dakwah di Indonesia #KembaliCeramah https://t.co/VWC7iwkmsB', 'geenrals', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (30, 'Kehadiran Gus Miftah Kembali Membawa Dakwah Toleransi dan Persatuan #KembaliCeramah https://t.co/cQbdNd4w9K', 'myooliee', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (25, 'Dakwah Gus Miftah Kembali Membawa Kehangatan di Tengah Masyarakat #KembaliCeramah https://t.co/P36NdPgXiB', 'phoettic', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (28, 'Dakwah Gus Miftah Kembali Hadirkan Keteduhan di Tengah Keragaman #KembaliCeramah https://t.co/f2cJoSJGS7', 'sooyounngrv', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (45, 'Gaya Dakwah Gus Miftah Kembali Menginspirasi Berbagai Kalangan #KembaliCeramah https://t.co/S8npUXy2fY', 'blondfe', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (49, 'Gus Miftah Kembali Dakwah yang Merangkul Umat Disambut Antusias #KembaliCeramah https://t.co/4KuMQ8W5vQ', 'Cecillia_agnes2', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (27, 'Kembalinya Gus Miftah Hadirkan Dakwah yang Merangkul Semua Golongan #KembaliCeramah https://t.co/BWUW6K5nRM', 'amoreoss', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (26, 'Gaya Dakwah Gus Miftah Kembali Hidupkan Semangat Toleransi Umat #KembaliCeramah https://t.co/kMbGV0kd6X', 'baefawnv', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (38, 'Dakwah Gus Miftah yang Menyejukkan Hati Kini Kembali Dirasakan #KembaliCeramah https://t.co/WASC7giRsB', 'migrazsi', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@03__nakula Jamaahnya kenal dengan Gus miftah dan paham dengan candaan Gus Muliftah seperti kita dengan sahabat atau teman sepermainan pasti hal bercanda saling ledek kata Atau menghina udh biasa dlm pergaulan dan pertemanan seperti itulah dakwah Gus miftah jamaah di jdikan teman dan sahbt', 'MuhammadNa29081', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@ILCTalkshow Dakwah gus Miftah sesuai tuntunan rasulullah ya Pak. Istighfar lebih baik.', 'agusprib', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Vr1_Gim ini salah satu karakter dakwah kiyai pribumi kita salah duanya bisa dikatakan seperti gus miftah dan intinya isi dakwah mereka tak pernah mengkafir kaplingkan surga', 'BocahPekaJaman', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@JhonSitorus_18 @islah_bahrawi Klo nda paham ga usah olok olok jhon...gus miftah sering dakwah di lokasi pelacuran tempat dugem.. tempat yang selama ini dijauhi pendakwah ..benci boleh tapi goblok jangan', 'santoz92725', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Begini apakah Gus Miftah salah ya. Tapi jangan lupakan bahwa dia pernah berbuat kebaikan. Memang gaya lawakannya dari dulu begitu dan ini harus diketahui juga banyak orang akan datang berjualan di tempat-tempat dakwah dengan tujuan diborong ujar Deddy Corbuzier dikutip https://t.co/1q0Acb4ldp', 'akuratco', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@kegblgnunfaedh gus miftah ga pengen dikaitkan sm negara lagi jd lbih nyaman dakwah tanpa jabatan!harus paham kalian yg aksi!', 'b4c0t1n', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@Y_D_Y_P Gus miftah cocok dakwah disana kampanye kerukunan ummat', 'arbi_blues', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@Ki_Mulyono99 @Heraloebss Saya ikuti perjalan dakwah Gus Miftah memang banyak menyasar dunia malam dan golongan awam yg masih bercampur dgn maksiat. Jadi bahasa yg dipakai beliau tentu berbeda kejadian kemarin semoga membawa kebaikan bagi Gus Miftah keluarga dan jamaahnya.', 'jatmiko99604253', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@kompascom Salut buat Gus Miftah berani mengakui kekhilafan dg mengundurkan diri dari pemerintahan fokus ke dakwah di kalangan dunia malam saja lebih banyak manfaatnya drpd jadi pejabat.', 'AkmalDinan', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'korg ni kecam2 gus ni apehal tu mmg cara dakwah gus miftah mmg dakwah die tu cakap die keras sikit tapi dalam cakap keras die tu ade hikmahnya tu yg kita kene ambil kata2 enabler penunggang agama', 'amirulpaan8104', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@republikaonline Walaupun nasi menjadi bubur. Upayanya perlu di apresiasi. Jikalau Gus Miftah di lengserkan pun. Sebenarnya berkah. Bisa Melanjutkan dakwah nya.', 'ediganthol', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@msaid_didu Bang kalo orang Jawa becanda seperti Uda biasa Gus Miftah emang be dakwah dari nol dan beliau Uda lama membaur dg kalangan bawah gaya bicaranya juga ga bisa kaya bang Didu di tata JAIM beliau TDK bisa seperti itu. Kesalahan beliau terima jabatan karna pejabat harus JAIM', 'SuhariToris', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@RoyaniNurhayati @satriohendri Lhaa dr dl juga gaya dakwah gus miftah emg slengekan gitu. Dia kan dakwahnya di lokalisasi dan cafe2 gitu cara penyampaianya yaa dgn becanda dan rosting2 gitu.', 'geraisurya', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@ike_hw71 dakwah gus Miftah dr dulu banget begitu krn segmen dakwahnya ke gol umat yg terdiskriminasi sosial jd mengikuti gaya komunikasi konstituennya. kini jd pejabat publik bisa jadi amnesia ada protokoler ketat soal adab komunikasi formal ya...', 'Na_Rational', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@es_teroz @dedemit_bulan @kegblgnunfaedh Ini konteksnya lg bahas da''i yg sama2 ngehumor dlm dakwah. Gus Miftah dan Zainuddin MZ yg satu ngebully utk ngelucu yg satu nggak. Itu aja perbandingannya. Kalo kamu suka dakwah yg serius yah silakan.', 'ika_hi8', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@aldibawazier_ Dulu gus iqdam skrg gus miftah dulu juga ustadz das''ad latif.. Besok siapa lagi??? Orang yg sering datang ke pengajian gus miftah pasti tau gimana metode dakwah beliau gimana candaan2 beliau.. Dn ketika viral.. Orang lain tersinggung.. Aneh', 'PengabdiTantan', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (105, '@zarryhendrik Seperti Gus Miftah? Gaji gw cuma 10%nya dia gw ga bs dakwah gw ga kenal sama pemerintah yg follow gw dikit ga punya ponpes gw ga punya jabatan sbg utusan presiden. Sama?', 'roy_pradipta', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (4, '@pgmoraaji Yang saya tau dalam dunia dakwah diIndonesia yang bisa masuk ke dunia malam/diskotek dan sejenisnya baru 2 1. GUS MIEK 2. GUS MIFTAH silahkan kalo mau menambahkan', 'ghufy82', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Gus @miftah apakah gaya dakwah nya berubah kaya Ustadz Maulana', 'm_trinurrizal', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Jadi sebenarnya emang karakter dakwah gus miftah seperti itu wkwkwk kok malah dibela dan membenarkan. NGGA ADA DAKWAH YANG KAYAK GITU YA!! RASULULLAH NGGA PERNAH NGAJARIN UMATNYA UNTUK BERDAKWAH SEPERTI ITU!! JANGAN MEMBENARKAN HAL YANG JELAS SALAH!!!️', 'kymshuset', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@tekarok007 Gus miftah orang baik Bahasa memang cenderung sarkas di karenakam area dakwah beliau di kalangan malam sehingga semua di anggap kawan.saya respect ke beliau cuman sayangnya kebiasaan itu terkadang di bawa pas tabligh akbar.sehingga orang awam banyak tersinggung', 'AminAman10', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@Gerindra Ayo Gus Miftah banyakin acara dakwah kayak gini biar rakyat kecil langsung dapat Bantuan Tunai yang tepar sasaran', 'rnbgelora', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@KompasTV Emang Gus Miftah punya style suka bercanda. Di setiap dakwah nya. Mungkin dg kejadian ini Gus bisa intropeksi bahwasanya perkataan yg menyinggung perasaan mulai di buang. Semoga Gus tetap sehat.', 'ediganthol', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@akbarfaizal68 Gelar dan jabatan tinggi sekalipun diantara kita semua..... Mgkin hanya sedikit yg faham Jika Gus Miftah ini adalah seorang wali Kalimat dlm dakwah yg dianggap banyak orang adl mencaci menghina dan merendahkan Justru sebaliknya yg diperoleh dan didapat oleh penjual es', 'past_ramudeng', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (68, 'Emang begitu methode dakwah Gus Miftah dan wajar-wajar saja! kata Barisan Sang Pembela Miftah. #Ngik https://t.co/TglBL5V6UU', 'HumorJonTampan', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@dodi119mx @yusrilfahriza Tp dakwah skarang banyak komedinya sbnernya dridlu juga sih contoh kyai Anwar Zahid. Kmaren waktu gus Miftah diundang pengajian ditempatku gua denger ayo ndelok gus miftah wonge lucu ada yg orang dateng nyari lucunya. Mungkin ini efek klo dakwah kebanyakan ngelucunya.', 'lukakitalukamu', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@tsrid_ @_mardial_ Klarifikasi beliau ini bener memang tipikal dakwah gus miftah seperti itu tapi buat orang awam kaya kita dan penjual es tsb ya sakitt sih digoblok2in', 'ciderahh', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@UmarHasibuan__ Itu hanya candaan dr Gus Miftah anda hrs tahu model dakwah beliau kan seperti itu guyonan bahkan kadar agak saru anda hrs paham &amp; maklum beliau itu penggemarnya jutaan lho kslobanda tdk percaya silahkan share videonya lg yg lengkap buat tdk gagal paham', 'AliMasy99072083', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Boediantar4 Gus Miftah mana nich.... Posisi nya sekarang bisa lebih kuat lho buat dakwah. Apalagi cuma buat nangani masalah MIRAS.', 'IqbalsahidAbdu1', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Dosen gw mengatakan bahwa Gus Miftah ini adalah seorang Da i yg menargetkan Anggota Klub Malam sebagai Obyek Dakwah. Beliau menggelar Tabligh di Klub2 yang membuat anggota klub trsebut berusaha mengenakan pakaian yg Pantas karena Ustadz mau dateng', 'Ahrifkys', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@__AnakKolong Gus Miftah adalah insan yg amat cerdas dihormati seluruh warga dan dijadikan panutan generasi muda syukurlah beliau dijadikan pejabat tinggi agar bisa jadi guru bangsa sy juga mendukung Gua Miftah safari dakwah keliling ke sekolah2 di seluruh Indonesia unt sebarkan kebaikan.', 'wrahardian2', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@ethadisaputra Gus miftah itu ulama..mengajak kebaikan..kalau da orang g suka cara dakwah y jangan malah disukurin.. cari pndakwah yg sesuai selera kalian.. ingat Tuhan nya sama nabi nya sama solatnya sama.. puasanya sama zskatnya sama dan haji nya juga sama..', 'Rajakemulan', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, 'Gus Miftah ya? byk org menghujat beliau karena salahsatu video dimana Gus Miftah menggoyang2kan Kepala Istrinya. mmg klo logikanya itu salah. Tapi trlepas dari itu setelah gw diberitau dosen gw ttg Pandangan Ilmu Dakwah terhadap Gus Miftah Gw jadi sedikit penasaran ama beliau. https://t.co/UFpaSWM8gl', 'Ahrifkys', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Mdy_Asmara1701 Gus Miftah memang bisa diandlkn kalau dakwah di bidang perlontean dan dunia malam seperti yg pernah dia lakukan di jogja...semoga lonte2 itu bisa tobat dgn adanya dakwah dr Gus miftah tp kalau urusan toleransi belum saatnya', 'R_togog180782', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@ekagumilars Gitu Gus Miftah dukung Mas Gib di cibir kader2 pdhl Gus Miftah juga demi dakwah juga. Dah mang benar politisi itu inkonsiten dan hipokrit.', 'Saldesa_INA', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@kliens78 @kepobanget_ye Syg nya ini video potongan buat ngeframing si gus..video aslinya panjang justru si gus ditempat2 tsb dakwah.bukan belain si gus tapi nyatanya dlu dia emg terkenal berani dakwah ditempat2 yg gak smua ustad bisa kesana..tp ya tetep gra2 gobl*k akhirnya skrg dia nya sndri yg gbl*k.', 'DimasPerwira06', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (3, 'Setiap genre dakwah saya pikir baik. Ada Gus Iqdam Gus Muwafiq Gus Miftah Gus Baha Gus Ali Gondrong Kyai Anwar Zahid Habib Sech Ustadz Safiq dan Riza Basalamah UAH UAS dll. Yg penting tujuannya utk mendidik umat islam. Jangan saling mencela.', 'ToufikImtikhan2', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@TukangBedah00 Keren Gus. Bocah yen ora faham dalan dakwah mesti nyocot ora kepenak di guyu mawon namine bocah. Aku Bangga lahir wonten Jawa Timur.', 'adi_supria24794', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (3, '@ust_muslih Damai tenteram gus. . Wong Tulungagung sdh memberi contoh bertindak nyata unt mensterilkan daerahnya dari dakwah Habib2... https://t.co/pvtIaZ8rvp', 'ntar_yaa', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Gus_Arifin Itu di jalanan kampung gw emang cah kampung kenapa? Lu kota mana sih? Sekota apa lu? Dakwah mu cuma seujung kuku dia tau! 999 hal baik kau tutup mata 1 hal gitu kau hebohkan munafik. Lebih mulia dia dibanding lu yg cm ngbacot di sosmed! Kalo lu gak terima siap ketemuan gw!!', 'haryleywibowo', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@mx00711 @agama_nusantara @sakkusaitna @BayuAngora @PaijoKhentirr @Valhallaah @spektrumku @Kappa_2023 @bnsphrxyzzz @RefublikAteis @JohnBanting03 @JohnAarivEd pernah ada yg bilang beliau itu gus diskotik. nah ini nambah lagi gus sarkem? gus dugem? banyak bener gelarnya. ya semua udah ada pangsa pasarnya sendiri2. bahasa etika adab ya ngikuti di mana dia dakwah kan. seharusnya justru mencontohkan yg lebih baik. *gelar gus itu sakral', 'iphone7decoco', 1);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@JhonSitorus_18 @islah_bahrawi Klo nda paham ga usah olok olok jhon...gus miftah sering dakwah di lokasi pelacuran tempat dugem.. tempat yang selama ini dijauhi pendakwah ..benci boleh tapi goblok jangan', 'santoz92725', 1);

INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@NinzExe09 @prabowo Terlepas dari soal kemarin Gus Miftah adlh tokoh yg berani terjun ke wilayah marginal. Berdakwah kepada mereka yg diasingkan dari dunia dakwah itu sendiri. Semua ada plus minusnya.', 'ToufikImtikhan2', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@erfansrsaleh @ARSIPAJA Tapi terlepas semua ini niat Gus Miftah untuk langsung klarifikasi dan minta maaf itu menurut aku keren banget. Dengan ciri khas dakwah beliau yang frontal seperti itu tapi dia masih mengakui kalo beliau salah. Semoga di kedepannya beliau bisa lebih baik lagi.', 'yanggaaaaaa', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (58, 'Karena memang karakter dakwah gus miftah itu seperti itu saya tidak bisa menyalahkan juga Apakah tidak ada cara lain untuk berdakwah sehingga harus menyakiti perasaan orang? Dakwah harusnya membawa kebaikan bukan dendam.', 'jackjackparrr', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Rizieq_Sangean @Purnomodttrad52 Ini kan gurunya Gus iqdam dan Miftah', 'law20956', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@AndyHuskyyy Gus Miftah dakwah', 'IniHiruma', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (185, '@tanyarlfes mantap kali gus gus yang buka bisnis waralaba dakwah ini.', 'direktoridosen', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@tanyarlfes Gus gus mustinya anda dakwah dari satu tempat ke tempat lain tuh naik kuda aja naik kuda naik kuda juga enak', 'Alm4dahtau', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@SayaGenZ @robby_karman (Gus) Miftaf? Aku sih tipe yg jujur ya hehe yang sering baca aku debat/menanggapin konflik bisa nilai sendiri. Nah terkait beliau itu gak cocok dgku dia dulu keramat (dipandang terhormat) karena mampu deket dg tokoh2 hebat dan cara dakwah kayak Gus Miek setelah itu putar', 'santri_keliling', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@TukangBedah00 Tinggal belajar dakwah trus pake nama gus', 'KingNvhOfficial', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@RlFKEY @AndyHuskyyy @txtdrimedia Jatim/Jateng khususnya di kabupaten. Dimana mayoritas warganya itu tidak bersosial media dan sesepuh mereka masih percaya dengan ajaran dakwah/kajian pada kyai-kyai setempat atau turunan-nya yang biasa kita kenal dengan Gus ada pada nama depannya.', 'raskontl', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@PatubMbel NU yg saya tau ya yg dakwahnya dan kiainya bisa berbaur dgn adat istiadat dimana mrk dakwah. biyen sempet respek bgt ro NU kiyaine sangar sangar basan saiki kok nemen bgt. mugo wae niate gus baha iso berhasil.', 'NurHendra_', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@eddictiveX @V3g3L @hipohan Yaaa melihat siapa yg isi dakwah itu baik di tmpatku jogja malah gus habib isinya sholawatan dakhwahnya hanya sebentar', 'wawansiwe23', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kali ini publik lebih menyoroti gaya dakwah Gus Miftah yang dianggap berbeda dengan pemuka agama lain.', 'suaradotcom', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, '@aesculapiusw @itsmeeerun Iya nggak papa lho mbak kalau tersinggung saya juga nggak maksum masih suka bikin dosa masih suka tersinggung/tersindir sama ceramah/dakwah tp y gpp tandanya ALLAH masih kasih saya iman dan hidayah. Saya mah asal nggak macam pengajiannya gus miftah dkk ttp mau dengerin si.', 'Nadd_yas', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, 'Gus ..Gus Dakwah itu yg penting isi ceramahnya bukan Gus nya ! https://t.co/rikMMKH4ah', 'Ghurem2', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Mdy_Asmara1701 Soalnya bisa ngaji kitab dan punya santren easy kok kalau mau punya gelar gus atau yai. Intinya harus pinter dakwah dimanapun kapanpun bersama siapapun. Nafas adalah dakwah', 'MIchwannuddin', 2);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, '@BalimbingJ @NyaiNeneng Gak semuaa kyai Gus ga semuanya seperti apa yg lu sebutin. Gus baha Gus najih kyai Maimun kyai Idrus Ramli Buya Yahya. Dakwah mereka adem ayem dan coba ikut ta''lim habaib dari majlis dakwah yg Udh masyhur ceramah mereka adem kok jangan langsung menggeneralisasi!!', 'Ayumichan901', 2);

INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Para gus-gusan juga ini aduuuh kejadian sendiri di aku soalnya waktu adekku yang SMP ngomong kasar ibuku malah jawab gapapa ngomong kasar wong gus miftah aja dakwah juga ngomong kasar', 'TanggapanH', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Stakof Harusnya intropeksi Gus Miftah ga semua orang menerima dakwah kasar model gitu', 'SatrioDicaprio', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Serius gus miftah ngomong begini?? Ini acara apasih? Dakwah Agama atau apa sih?', 'kenjuwuw', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (5, 'jadi sering lewat clip dakwah gus miftah banyak yg fucked up dah emg becandaannya mksd gw di tongkrongan bahas gituan udh dicap sangean pasti', 'ahmagernyet', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'gus miftah emang bercandanya gitu daridulu INI BERCANDANYA??? INI??? NGELECEHIN ORANG DI DEPAN UMUM DI ACARA DAKWAH??????????', 'esekubse', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@djadja222 @particularshape @Hiken9700 @satriyotutuko @UmarHasibuan__ Lah emg dongeng kok buktinya kmren Gus iqdam sma Gus Miftah kajianya dongeng mlu gk ada nilai kandungan Islamnya', 'RivaldiFaza', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'gue bersyukur kehidupan gue jauh dari fenomena gus gus an macam ini. i''m so blind at first then boom! gus miftah gone viral and i think i am blessed in this case.', 'sepatubulan', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, 'Astaghfirullah gw benci bgt Lan Wangji di downgrade jadi Gus Gus an anjim. Nasab itu dihitung dari Ayah. Lu semua berhenti deh maksain mau ngindolain keturunan Nabi palsu apalagi yg kek Gus Miftah. Maksa bgt pengen sosoan bangsawan mulia najis gus gus ew. Trauma liat kata Gus', 'voiceS_Yoongi', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@spittedkink Wkwk jd pemuka agama yang aneh2 juga ya berarti pake demen flexing lagi waduh Gus Miftah kenapa tuh?', 'mrscuttlebug', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@TirtoID Jadi ingat kasus es teh nya gus miftah. Semua orang nawarin si bapak tukang es teh untuk umrah beasiswa dst dst. Termasuk Gus Miftah sendiri yang selfie sambil peluk dan rangkul si penjual es teh. Polanya emang gitu kali ya?', 'Aryghosie', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@SuryonoSyarif Ga cuman mereka gus gusan nusantara juga bisa jadi duit buntine miftah sukses', 'eagleOn89420268', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@ferizandra Yah dari kelompok ANUS lagi. Aliran sesat Aliran Nusantara atau pbnu. Gas gus gas gus padahal dukun tak berilmu kayak si miftah contohnya. Wajar lah', 'al_khalid212', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (9, '@kakraran @gassskeuun @ferizandra Uas bahasanya simple kok mudah dimengerti. Gus baha apalagi bahasa yg sangat enak didenger buat masyarakat jawa dskt. Ga perlu mikir2 amat mereka aja yg hobbinya modelan Si Iqdam ama miftah. Kl ada yg harus bayar knp harus milih yg gratis dan simple. Gitu kali ya?', 'MbemLover', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (10, '@ferizandra Iqdam pasti cari alasan buat infaq Pantas Gus gusan itu kaya kaya krn PD jualan agama Ya kaya si Miftah sama iqdam Modal kopyah sama sarung doang terus apal alfatihah doang dan apal satu dua hadist langsung jual agama Ceramahnya pun cuma cerita cerita lucu doang', 'law20956', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (703, '@ferizandra Dikasih ustad adi gus baha UAS ustad oemar mita buya Yahya malah ikut pengajian iqdam dan miftah bayar pula ckckckckck', 'gassskeuun', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Xoxo1447630 @ShamsiAli2 yg kayak gini udah mirip ama yg jualan agama kayak gus teh miftah. pasti dia panutan lo kan soale ga kabur kemana2 di jawa aja jadi penunggang agama', 'sosmedulti', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@AdindaZahrany07 Seems like never seen this in Gus Miftah tragedy pantesannn ajaaaaa ada Gus gus-an ini. Ternyata kepala yg diikutin begini modelan nya', 'bellabeele', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@ferizandra Idham miftah anak ajaib gak jelas mengaku NU dan merusaknya secara terang terangan di akar rumput dengan konser konsernya. Yaqut yg punya darah NU dari orang tuanya malah diduga korupsi dana haji. Sekarang orang NU yang bisa di percaya cuma Gus Dur dan Gus Baha', '7dosabesarr', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@CNNIndonesia kayaknya di NU makin subur oknum2 gus2an penunggang jualan agama ya gus miftah gus ini belum nu yg pergi ke israel abis itu nu cuci tangan tp masalahnya mreka kan belajar agama tp knp munafik', 'sosmedulti', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@CNNIndonesia salah 1 gus2an selain gus teh miftah penunggang jualan agama ga jauh beda dari kriminal malah lebih buruk karena menyesatkan orang', 'sosmedulti', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@SammiSoh Trus mau nya aja ajaran islam yg ala gus miftah dan gus iqdam yg menoleransi kemaksiatan &amp; kemungkaran Kok bs gerombolan perusak agama dibiarkan &amp; menjual agama demi hawa nafsunya #NegeriParaPenipu https://t.co/JFrlAmZEgV', 'HidayatMazz', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (46, '@CNNIndonesia Gelar Gus sudah seharusnya disortir. Segelintir sampah pakai Gus : Miftah &amp; Iqdam sudah merusak gelar Gus. Kasihan orang baik dan hebat kayak Gus Dur harus disejajarkan sama makhluk sampah Miftah &amp; Iqdam.', 'desmodromici1', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Ga semua Gus jg sih yg agak nyeleneh yg w temuin baru gus miftah &amp; the genk trs siapa tuh ustad yg motoran bilang palestin baik2 aj idih', 'Leewdoongwook', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@36Dpib12339 @islah_bahrawi @gagal_hijrah Wahaha undangan2 kepada penceramah saya yaqin kok buka masalah keilmuan tapi karena terkenal Yo koyo TAIM alias Gus Miftah diundang ngisi pengajian bukan karena KEILMUAN tapi karena VIRAL dan VULGAR', 'ust_muslih', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (6, '@callmecalis @MALAYSIAVIRALLL Sebab konoha sesat beramai2 raya awal seminggu gus miftah yg banyak melecehkan depan public dikata bikin adem gua tembus p mekah la selawat pun siap joget2 dibuat mcm hiburan pastu siap boleh call Allah lagi', 'greentea06_', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@ilyisyanatungga @Melati_Hani @NotChaPlainJane Ya saya pernah nampak event di YouTube ada kiai dengan gus yg sama geng dengan gus Miftah itu siap merokok2 sambil selawat. Itu sudah sesat tu. Nabi Muhammad saw tidak mengajar kita merosakkan diri sendiri dan orang lain.', 'jannahheaven247', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@DewiPutriku06 @Userword_ @sarahbae94 @SmudgeStan Justru muhamadiyah ajaran2 Islamnya bener GK kaya NU liat ulamanya aja kgk bener malah menyesatkan contohnya Gus Miftah sma Gufron dan habib ba''alawi itu ulama yg cuman ngandelin dongeng2 kyai2 doang dan gk ngajarin nilai2 islam', 'RivaldiFaza', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@toe_giman Tapi kyai NU ga pernah ngajarin ngehina orang guru ngajiku dikampung ga pernah ngajari kayak Gus Miftah', 'Piomonn', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (19, '@reezethegreat @tanyakanrl Gara2 pak miftah ya gus yang betulan gus jd jelek gus itu nasab anaknya kyi atau yg pemimpin pesantren klu bahasa jawanya gus itu cah lanang bagus tampan', 'amy_cleo10', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Rizieq_Sangean @Purnomodttrad52 Wkwkwkkwk org yg kek gini Di Videoin di kasih judul Gus Adik nya si Miftah yak ..', 'erikhansa78', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@tanyakanrl Gas Gus Gas Gus bocah ingusan pada disembah. Heh goblok tuhan noh lu pada sembah bukan manusia sugus lu puja puja dongo... Paling ujung2nya cuma jdi kayak si miftah brengsek itu', 'Jemsbray', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@DewiPutriku06 @particularshape @djadja222 @Hiken9700 @satriyotutuko @UmarHasibuan__ Banyak kyai2 NU yg kaya gtu dan habib2 NU jg gtu contoh kecilnya habib Bahar itu kan sekaum sma lu terus pesantren nya Gus Miftah istrinya ngajarin perbudakan dengan nyebarin makanan ala2 kolonial belanda', 'RivaldiFaza', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@id_lgk Muridnya gus miftah ini rada gila', 'Mild1619', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, 'Masalahnya @prabowo ngomong NDASMU di forum para menteri. Dedi Kobuser ngomong PE''A si Ta''im atau Miftah gus palsu ngomong GOBLOK. Rasah nggarai wong soal etik wong pemimpinmu saru.', 'Div_HumasParcok', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@hceavens maaf ak gasuka gus²an malah kebayang gus miftah kalo baca', 'ourrbluee', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@AtutiAtut @dr_koko28 Aku denger kajian nya gus miftah kek jijik bgt kata2nya ga pantes buat dakwah. Gitu jamaahnya ketawa2 astaghfirulloh miris', 'sepatubulan', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@ABokshouw @alfaarell @fluttersyabell @surga @dastanjr @aidenduts @Bull_winner Damn kok kemana2 si lucu banget haha. Kita bahas HAM dari tadi. Dan lo nggak tau apa gus miftah pergi dakwah sana sini bawa nama prabowo dan ngasi uang. Jangan tutup mata hampir semua emang pake politis identitas karena di masing2 paslon punya ulama.', 'skilloebarcumbi', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Cecillia_agnes2 Gus Miftah bikin kita mikir dua kali sebelum mengambil keputusan dukung dakwah positifnya.', 'alif_reynaldi14', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Dari kasus Gus Miftah kita belajar bahwa yang namanya Dakwah itu merangkul bukan menghina.', 'zahroenzee', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'anjir lah ini yg dakwah di masjid pake toa deket rumah lg bahas si miftah mana pake belain si miftah... idie najong bat.. kek mana sih pemikirannya naudzubillah sesat ngebela gas gus segitunya kaya lagi bela nabi ih...', '_ilyeri', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Tan_Mar3M Pdhal dia terkenal ya krna netizen sm penyanyi2 dangdut. Bukan krna pinter dakwah nya. Belagu bgt mau jdi the next miftah nih gus gusan', 'bayu_mika', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@tomiechains Kao konteks miftah artinya mereka (para gus yg sampe skrg msh belain) enabler. Melecehkan perempuan dianggap enteng doang bahkan mgkin diwajarkan. Ini hrs ditindak/ditertibkan secara struktural menurutku sih. Karena ternyata nama besar leluhur bahkan beban dakwah gak ngaruh.', 'asriprabasari', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (39, '@Pure_Monotheist @Flavumyellow cia giving better dakwah than Gus miftah⁉️', 'object478', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (39, 'Gus Miftah dan gus² plastik semacamnya emang ga pantas jd pendakwa. Sdh cocok dia dihilangkan dr panggung dakwah tana air https://t.co/METtWEIp54', 'Munir_Timur', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (21, '@Gus_Arifin Tuduhan iqdam ke netijen (termasuk saya) : -Membenturkan tokoh -Tidak pernah ikut pengajian . Dhuh padahal kemarin berniat agar Miftah itu kembali dakwah dg baik &amp; benar. Dia ditegur Allah SWT dg cara yg sangat ajaib hanya didiamkan penjual es teh setelah meledek.', 'yogazzzt', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (22, 'Dilakukan Gus Miftah Apa Hukum Guyonan Pakai Kata Kasar dan Saru saat Dakwah? MUI Bilang Begini https://t.co/pQGebMdeL7', 'OposisiCerdas', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'imo tuhan ngingetin gus miftah kalo dakwah jangan pakai kata kasar meskipun tipikal beliau dari dulu seperti itu. sekaligus ngasi banyak rezeki ke pedagang es teh.', 'blwndosqy', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@democrazymedia Zaidan dakwah Abal Abal karbitan ngaku ngaku juga 11 12 sama Miftah sepuguruan Dakwah gak bermutu suruh ngaji lagi Zaidan kembali ke Alif maaf bagi saya haram hukumnya memanggil dia Gus atau Habib soalnya dipertanggung jawabkan di akhirat nanti. Copot gelarnya', 'f95013', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@KissT34899 @geloraco Sebelum Miftah ada Gus miek. Tp Gus miek masih lemah lembut dg sesama lah klo si Miftah kayanya kebiasaan disana malah jd kebawa pas dakwah', 'xndmsdh_', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@JhonSitorus_18 @islah_bahrawi Klo nda paham ga usah olok olok jhon...gus miftah sering dakwah di lokasi pelacuran tempat dugem.. tempat yang selama ini dijauhi pendakwah ..benci boleh tapi goblok jangan', 'santoz92725', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@geloraco kegoblokan apalagi ini logikanya di pakai umur gus miftah sm gibran tua siapa lama siapa di dunia dakwah hoaks lago hoaks lagi', 'BudiYulian26978', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@kegblgnunfaedh Suruh Gus Miftah berubah dulu deh Gk cocok soalnya dakwah tapi gk pake adab', 'AgoodMood16', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Mpun mboten nopo2 pak. Tasek katah kyai2 NU sing sae. Gus Miftah menurutku lue apik kyk bien. Gaya &amp; cara dakwah sesuai panggonane. Kabeh duwe Habitat &amp; kapasitas dewe2. Gusti Allah wis Ngatur', 'WardanaSCandra', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Kemaren kayaknya ada petisi nurunin gus gusan ini. Ada petisi biar ngga usah dakwah dan ngga usah jadi utusan presiden ngga? #petisi #sonhaji #miftah', 'lienarainarra', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (7, '@lampuhijau012 @dihkiiw__ terus juga contoh dakwah yg masih belum tepat tapi sayangnya masih masif itu dari kasusnya gus miftah dkk. masih banyak loh yg mendukung beliau artinya kritisi terhadap dakwah yg kurang tepat belum efektif utk menyadarkan muslim lain', 'greyslayerr', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@ezroadtax @hidupberbakti Ntahnye. Benda simple je dia p kona buat apa. Memang gus miftah tu bahlol dan uai ni bukan. Tapi dua2 menggunakan perkataan yg mencela dan memburukkan orang. Kita duk debat pasal perkataan yang digunakan. Tak kesah lah mcm mana pun. Gunalah word elok skit. Dakwah kena berhikmah.', 'shafiqi00932621', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@ahmad_bellamy @yusuf_ch ada yg bela guyon dan karena berasal dar rakyat kecil RASULLULAH Saw dan para sahabat juga dakwah ke rakyat kecil ada AL QUR''AN dan Hadits shahih yang membenarkan kelakuan Gus Miftah? Prilaku gitu justru menunjukkan karakter ybs. GA USAH NGAWUR', 'herman_chou73', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@neVerAl0nely Kalau disebut ndagel atau dagelan ini ok banget seru dan suasanya hidup. Tapi kalau disebut dakwah ini ga cocok. Jadi kalau menurut saya Gus Miftah a.k.a Kang Ta''im itu seorang pelawak. Saran saya lebih baik diseriusin jadi pelawak aja itu lebih menghibur dan bikin happy.', 'violettapadma', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@yeerimc Orang2 yg memberi pembelaan pada Gus miftah berarti orang2 tsb tidak mengerti ajaran Tuhan di mana Tuhan melarang umatnya untuk menghina dan mengkafirkan orang.inget Dakwah ini bukan ketoprak atau komedi', 'JayaRinggo8170', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (9, '@meissasinna @satisfactorili @izdsy loh sama halnya dgn gus miftah dong. blio gaada background spt yg dirimu sebutkan tp mata pencahariannya dari dakwah bahkan ga jarang bawa2 hadist juga. hayooo', 'choconoirr', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (37, '@toddysolo79 @hhsahal Tapi Umar bin Khatab gak pernah menghina perempuan loh guyss dia sama binik nya aja takut beda lagi di Medan perang. Lah ini si Miftah sekolah gak lulus ngaji gak sampai yang ngundang dia Gus awal nya siapa sih Najisin sekali kalo dakwah tapi dibayar bukan karena ikhlas', 'Jungnan1098', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Uhuuuy_ nah makanya ituuuu padahal ulama2 NU yg lebih senior kaya gusmus mbah moen yai maruf cak nun dsb justru kalo dakwah bener2 selalu pake tutur kata yg sopan dan santun lah ini si miftah ntah darimana asalnya bisa dipanggil gus tapi kelakuannya kaya gitu hadeh bikin malu NU aja', 'vexanca', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (12, '@tanyarlfes it''s time to stop glorifying gus gus yang gak jelas nasab dan keilmuannya. dr dulu liat dia dakwah pake kacamata hitam sambil bawa teken aja udah aneh. banyak dai yg udah sepuh aja gak bawa teken sambil nunjuk2 jamaahnya. nir adab kayak miftah kok dijadikan panutan', 'kaamilael', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (28, 'Dari dulu kok lebih suka Gus Baha berilmu tinggi sopan benar2 dakwah. Tapi kalau banyak yang suka miftah ya begitulah selera Masyarakat Kita https://t.co/Y3s1IRFjz2', 'soeyoto1', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Gus Miftah lebih sering dilihat dalam konteks politik daripada dakwah yang seharusnya mempersatukan umat. #Miftah', 'RentalM50413521', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@4zmeela @tanyakanrl hahaha ituu si gus miftah pas dakwah kemarin ngatain goblok ke bapak yg jual es teh kak trus karna dihujat netijen si gus miftah nyamperin bapaknya buat minta maaf sekalian diajak collab itu deh cmiiw', 'HoneydaIliyina_', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (25, 'Juru Dakwah Perlu Disertifikasi Jangan Ada Lagi Penceramah tak Beradab seperti Gus Miftah https://t.co/KaXS5jJM9b', 'OposisiCerdas', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@herricahyadi Miftah menciptakan genre baru dalam dakwah : dakwah porno', 'Sukirman2019', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@islah_bahrawi inget kejadian gus nur ndak gus? yg nyleneh sukanya joncak jancuk kl dakwah? sama kam sm (gus) miftah ini? akhirnya sama2 kejeglong sm kelakuanya sendiri menurut sy dia star syndrome shock culture hingga menjadi megaloman', 'nomeats', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Stakof Beda jauh Gus Baha sama Miftah Gus Baha emang fokus dakwah sdngkn Miftah haus kekuasaan', 'Xbreaker9999', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@MisbahAliah19 @ARSIPAJA Emang Nabi dakwah lu penah liat atau dgar dalam hadis atau Quran beliau menghina orang lain? Malah yang bukan islam aja dia gak hina dia bicara baik baik dengan lemah lembut. Emang gus miftah lu darjat nya tinggi? Goblok', '_sam508', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, 'Gus Miftah kalau mau becanda sama circle anda aja yaa. Jangan dibawa ke dakwah. Malu-maluin agama sendiri', 'modall_lucu', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@aewin86 Lah gmna si? Itu si miftah pemuka agama dengan gelar yang katanya Gus yang seharusnya memberikan contoh yang benar ke masyarakat. Noh diagama islam tuh adab lebih tinggi dari ilmu dengan gaya dakwah kayak gitu aja menandakan gaada etika. Jangn ke agama deh dasar negara kita', 'dreamsfornova', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '''memang karakter dakwah nya gus miftah seperti itu'' lah mas situ wes ndelok dewe karakter nya jelek kaya gtu kok yo malah di ikutin kajian nya? jelas2 dari akhlak si ''gus'' miftah ini udh jelek ga punya adab sesama manusia. kok yo malah di ikutin dan dijadiin tokoh yg diagungin', 'mrklsyfm', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (6, '@adeirra Pengen jualan es teh pas gus miftah dakwah. Biar aku digoblok²in juga oleh beliau.', 'kyai_ambleg', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@_Marlboro1 Ki lho sohib e miftah. Gaweane mendem staycation kok diundang gus. Wong ra beres kok dikon dakwah. Kui awale nang sarkem jur dodolan lambe. Ngerti nggon lendir akeh duite. https://t.co/7KqmCvuXSK', 'bacabacaupdate', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@JhonSitorus_18 Paling enak tetep dakwah nya anwar zaid gak kaya gus miftah ini yg penjilat', 'anggaalfian345', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@JhonSitorus_18 karakter dakwah seperti ini?lantas apakah Gus Zidan Yahya juga membenarkan sifat Gus Miftah yang mengolok ngolok dengan kata goblok Ternyata lidah lebih tajam daripada pisau yang diasah', 'DaisyFlow41', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (960, '@akbarfaizal68 Miftah itu Gus Palsu buatan dan binaan PKI makanya ajarannya nyeleneh ! Boikot dakwah ngaco si Miftah dan minta presiden @prabowo copot jabatannya krn si Miftah membelah umat dan rakyat. Tangkap dan penjarakan miftah Gus palsu #AbolisiBubarkanPolri #GoblokMiftahRasaMuntah https://t.co/EGfwoOrG8a', 'M4kzulk4nFu2fa2', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'awokawok dri kemarin diem aja tp batin bgt kasihan pedagangnya yg msh kasih panggung miftah itu kataku gws deh dakwah kok modelannya begitu. mana dari dulu problematic gk cocok jd gus gus an', 'nabollalaxxx', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@tsrid_ @_mardial_ karakter dakwah macam apa yg menghina dan mengolok olok org lain??? katanya bnyak merangkul kalangan yg kurang baik? apakah bapa penjual es itu terlihat kurang baik di mata si agus miftah ini???? dah gila emg org org yg punya gelar gelaran gus agus ini', 'jayujinluv', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Miftah bajingan agama gak pantas mendapat julukan gus dia bukan anak kyai dan bukan dari silsilah yang jelas tuh makhluk makanya dia suka ke dunia pelacuran untuk memenuhi sahwat dia yang berkedok dakwah klu pendakwah yang bener tidak akan mengotori mulut dan lidahnya.', 'IbadAzka16', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@K_aji_99 @Cyb3rOG1 Udah gua duga pasti klarifikasinya gajauh dari kalimat jadi dakwah atau ciri khasnya Gus Miftah kalo dakwah itu begitu Basi lah', 'Bluerangers7', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'TAIM alias GUS GUS An MIFTAH. adalah penista menyembunyikan dakwah agama utk kepentingan ketenaran diri sosial dan penguatan politik. Dialah ulama yg hari ini bergelimang harta berkat ''kerjasama manipulatif atas ayat dan kuasa', 'nanangkmahasast', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@cingreborn Kok udah minta maaf aja ? Ga seru lah minimal bikin konten borong lagi di IG dan YT. Trus pas dakwah bilang GOBLOK lagi jangan minta maaf dulu kan punya gelar GUS. Ngapain minta maaf Miftah ?', 'danzega18', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@erfansrsaleh @ARSIPAJA Mungkin memang cara dakwahnya beliau seperti itu tapi apakah boleh menormalisasi hal hal yang kurang etis seperti itu? Aku rasa beliau sama sama lagi cari kerja dengan cara yang halal hanya takdir yang membedakannya di satu sisi mungkin Gus Miftah tanpa dakwah pun... (cont)', 'yanggaaaaaa', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@33unfolds @Cyb3rOG1 Minimal minta maaf gus @yusuf_ch ....tidak usah denial dengan istilah Wajar lah memang metode dakwah Miftah memang seperti itu lah guyonan lah kami tahu kalian memang dekat dengan penguasa tapi rakyat sedang dalam ekonomi yang sulit macam sekarang sy yakin lebih gampang emosi', 'wiwithyulianto', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Cyb3rOG1 yg bener2 real gus dan dakwah untuk umat islam ya gus baha sih. heran masih bnyk bgt yg ngasih panggung buat si miftah keliatan starsyndrome udh sama istri sendiri aja kasar gada adab.', 'aissthethic', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@kadangbablas @CNNIndonesia Terinspirasi dari dakwah Gus Miftah', 'maskcu', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, 'metode dakwah mana yang asal bilang goblok ke orang apalagi ini ke orang tua yang lagi berusaha cari rezeki halal. si miftah emang pure minus adab. merasa dia lebih tinggi karena berilmu padahal arogan. apaan lagi dipanggil gas gus gas gus jembut lu mullet anjing', 'mmawardii', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@cingreborn Sebaiknya Pak Prabowo pertimbangkan pemecatan Gus Miftah dari jabatannya sebagai utusan beliau khawatir kedepannya kambuh lagi. Biarkan saja dia dakwah dengan caranya (sebagaimana dalam kehebohan dengan penjual es teh dimana gak etis) yang dikonsumsi para jamaah militan itu.', 'ghiffardana', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@UmarHasibuan__ Makanya Gus Miftah kita sbagai Makhluk Allah SWT yg hnya sebutir debu ini jgn prnah menghina org susah aplagi mnganggap remeh dunia berputar rezeky di tangan Allah jgn anggap canda apalagi rmehkan org di Depan Majelis dakwah! smua ada Konsekuensinya dr YME one day for you!', 'NinaOsie', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Langsung kebukti kan.. kyai gus habib ustad etc- yang isi dakwah nya minim moral &amp; ilmu kyk miftah malah bikin orang jadi ngejauh bahkan nyalahin agamanya. Ga heran framing islam makin ke sini makin ke sana krn yg dapet spotlights malah ulama2 macem gini dipuja2 pula', 'oldyellowfrick', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '1. Gus miftah ska merangkul kalangan yg kurang baik Kurang baik gmn maksud lu? Emang kerja dagang es gabaik? 2. Gaya dakwahnya emang gitu..spontan Ngatain org goblok gtu ya gayanya? Siapa yg dia contoh dakwah kyak gitu? Rasulullah gk pernah ya ngebodoh2in org kyak gtu.', 'ohnoonaaa', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Dear Untuk saudaraku . Semoga Tepat di Panggil Utusan Khusus Presiden @prabowo . Saudaraku Kyai/Gus / Ustadz Miftah. Pengasuh Ponpes Ora Aji . Mohon di evaluasi Lagi Gaya Dakwah Yang Jennegan Sampaikan. Terkhusus kepada Rakyat Kecil Pejuang Nafkah. Seperti Halnya Saya https://t.co/lAUE2Xv68O', 'Dilmil18', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, '@jasahack_sadapp @JhonSitorus_18 Dan temennya yang gila itu juga bilang kalau karakter dakwah gus miftah . Botol emang', 'archershoother', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@K_aji_99 @Cyb3rOG1 jadi karakter gus miftah tuh seperti itu dari dulu loh adab anjlok kaya gitu ngga bisa di normalisasikan lah?!?!?! sinting banget menormalisasikan penghinaan dengan dalih karakter dakwah seperti itu', 'st4rnus', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@yusuf_dumdum Yang jelas gaya bahasa Gus Miftah tidak bisa dipakai disemua kalangan. Klo dakwah di diskotik dan semacamnya silakan.. tp kalo di masyarakat umum tentu harus disesuaikan. Selanjutnya semoga masyarakat dpt menilai sendiri. Masih sgt banyak Da''i yg santun n adem bahasanya..', 'AbdulRo48557022', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Dakwah seger kan dakwah sambil ngintip dari bali kacamata hitam ya Gus Miftah. Alesane macem2 Dakwah sambil Ngintip paha dn dada lonte2. Jan mantap. Makanya tutur bahasanya ya dimiripkan olehNya dgn kaum lonte juga. Ujunge biasane ngaku sbagai wali Malamatiyah kayak yg udah2.', 'ABudisason5500', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@adiinyus_ Lihat video fullnya dulu baru kalau memang gus miftah emang begitu dan tidak ada etikad baik membantu berarti memang bejat tapi ingat kalau nonton fullnya kok gus miftah memborong semua minumannya itu memang karakter dia dakwah ya memang kurang baik tapi dia berniat membangun', 'TheLawlessX', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Gus Miftah biasa dakwah di tempat lonte. Maka oleh Allah bahasa dia disamakan dgn lonte2 itu. Rasulullah ngendika bahwa: Jika ingin melihat tabiat/ sifat seseorang maka lihatlah teman2nya. Jika teman2nya lonte maka itulah sifatnya. Hasil al ngintipun dari balik kca mata item.', 'ABudisason5500', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@JhonSitorus_18 Lihat video fullnya dulu baru kalau memang gus miftah emang begitu dan tidak ada etikad baik membantu berarti memang bejat tapi ingat kalau nonton fullnya kok gus miftah memborong semua minumannya itu memang karakter dia dakwah ya memang kurang baik tapi dia berniat membangun m', 'kharisaziz1254', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@RagilSemar gong coba usul ke presiden @prabowo minta gus miftah dijadikan menteri agama kayanya dakwah islam bisa dilukai dan akan semakin menurunkan presentasi pemeluk agama islam', 'ichsanfauzi6', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@MisbahAliah19 @ARSIPAJA Metode dakwah kek gitu ajarannya siapa??? Ngehina2 orang kamu yg ngebelain si miftah sama aja kelakuannya. Gak pantes di bilang Gus. Semoga Allah hinakan kalian yg ketawa itu didunia dan di akhirat.aamiin', 'anwarulmuniroh', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@yusuf_ch Mohon maaf kok gak bilang sama gus miftah dakwah kok di diskotik saya pikir itu sama. terlihat bukan tempatnya tapi sama sama yang satu niatan dakwah yang satu niatan cari rezeki buat anak istri. hal lain hanya Allah yang tahu.', 'airene_diary', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'mau dg embel2 cara dakwah atau apapun itu tetap tidak suka dg gus miftah iki rek kasian bapaknya anjirlah', 'xxrmalzd', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Dampak Psikis Dipermalukan di Publik: Dialami Penjual Es Teh yang Hadiri Dakwah Gus Miftah https://t.co/S0TSTFUKCI', 'IlfanG79396', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@tsrid_ @_mardial_ Ternyata pas liat lagi ini kajian setelah adanya huruhara Gus Miftah noyor istri didepan umum dan saat kajian ini justru melakukan ulang dgn dalih klarifikasi kalo ini bercandaan padahal sudah bnyk yg mengingatkan. Lagi- lgi berlindung dgn kata bercanda dan metode dakwah', 'Ihan261', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@yusuf_ch gausa ngomongin mengganggu konsentrasi pekara 1 org yg lagi jualan deh bukannya uda bertahun tahun dakwah dan ngadepin banyak org bukannya si gus miftah ini uda sering dakwah di club yg audiensnya warna warni kalo gabisa konsen gausa dakwah ade aje alesan lu', 'shittaccnt', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, 'yang bela gus miftah = bukan manusia gada salahnya nyari rezeki jadi penjual es teh meremehkan sebuah profesi bukanlah tindakan yg patut di banggakan. Gada ya yang namanya dakwah tp ngasi point ke satu orang dengan cara yg amat sangat tidak bermoral kamu berdakwah', 'weekndthird_', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@JhonSitorus_18 Jangan pernah manggil si Miftah itu pake Gus Gus an langsung aja MIFTAH pake Gus pula Gus syedihhhhh Gus syedihh bangeettt. Seperti itu kok dibilang karakter dakwah sudah melenceng jauh dari syariat udah ses*t itu adab dan ilmu agama nya msh dangkal.', 'marlina1362642', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (208, '@Cyb3rOG1 saya ngerti cara dakwah miftah emang gitu yang saya gak ngerti kog ada yg mau ngikut!!?? dari dulu kyai2 NU itu terkenal sopan dan sangat mengutamakan adab. kyai sahal mbah moen gus dur sampe gus baha itu masyaAllah lembut sekali dakwahnya.', 'kolektorGMC', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (6, 'Sangatlah aneh masih ada orang2 yang menormalisasi gaya komunikasi dakwah Gus Miftah. Menurut saya itu sudah sangat keterlaluan. Percuma orang berilmu tapi tapi tidak diimbangi dengan moral etika adab dan akhlak yang baik.', 'moon_astrophile', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@K_aji_99 @Cyb3rOG1 Jangan pernah manggil si Miftah itu pake Gus Gus an langsung aja MIFTAH pake Gus pula Gus syedihhhhh Gus syedihh bangeettt. Seperti itu kok dibilang karakter dakwah sudah melenceng jauh dari syariat udah ses*t itu adab dan ilmu agama nya msh dangkal.', 'marlina1362642', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@comebckhomee_ @Cyb3rOG1 Sama sekali tidak. Itu bkn cara Nabi besar kami Muhammad SAW mengajarkan dakwah. Nabi kami mengajarkan dakwah dengan lemah lembut bukan kasar apalagi menghina seperti miftah. Buat saya dia bukan Gus. Masih banyak Gus sesungguhnya yang patut dicontoh.', 'SUBSorbs', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Ngapunten gus pancen e miftah niku sebagai tukang dakwah sing bayaran e soko nyekel mik mboten pantes guyonan kados ngoten niku nek ditiru wong lak saru trus nek membudaya dakwah do cangkem e elek Kabeh pripun???? Nopo coro kanjeng nabi njih ngoten gus?', 'imdadhammad', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Lg rame bgt ya gus miftah. Di mojokerto juga ada GUS terkenal dakwah kemana2 pilkada kmrn juga ikut kampanye. Tp bayar angsuran susah kudu diajak gelut dulu sampe 2x di talangi https://t.co/Lsg2r2WVWa', 'BagasPutraN', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@yusuf_ch Ya namanya orang jualan yo opo seh pak. Kok bisa bapak menanggalkan logika buat bela gus miftah ini? Selama ini di acara dakwah/tabligh/sholawatan manapun emang ada larangan jualan es teh? Memang boleh mencaci maki org lain depan umum? Bolehkah mubaligh berperilaku demikian?', 'n8crwlr', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (16, '@K_aji_99 @Cyb3rOG1 Otak kalo udah kedoktrin disuruh makan tai juga mau wkw Jabtan gus kaya si miftah cm estafet keluarga kerjaannya jual agama dr bpk kakek moyang nya isi otaknya cm duit duit duit keliatan gd kt ikhlas klo ngisi dakwah jd ngomong seenak jidat Bagi bagi jg pencitraan cuih', 'sofyansmithhh', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, 'sudah bener gus miftah ini masuk politik saja wara-wiri jadi juru kampanye politisi soalnya kalo naik mimbar dakwah gak cocok selain ilmunya kurang dia juga gak bisa jaga adab', 'texRuly', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, 'Saat Ulama Gus Miftah Dakwah meng goblok kan penjual Es Teh walaupun dengan Guyonan mungkin beliau lupa bahwa tiap langkah pedagang kecil itu sedang ditulis sebagai jihad menafkahi keluarganya. Semoga Allah membalas hinaan itu dengan keberkahan berlipat bagi si Bapak Pedagang. https://t.co/wMudpX88KH', 'RohmadEndHer', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Sing jenenge dakwah yo ono adabe bib sampeyan dakwah melu ajarane sopo? Jo kabeh2 mbok tolerir kabeh yo ono watese tp lek sampeyan tolerir dakwahe gus miftah berarti sampeyan meyakini nabi ae mentolerir kelakuane si miftah iki. #habibzaidanbinyahya', 'doraygtersesat', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@K_aji_99 @Cyb3rOG1 Meski gitu makanannya diborong gus miftah lha mbo rene dibayar ngisi pengajian neng digoblok ne po yo gelem? Cara dakwah gitu merangkul org gabener trus boleh ngatain kepala keluarga yg cari duit dengan cara halal? Utekke lho cok', 'FDigitorum', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'mau videonya full kek atau engga kek ga mengubah kalo omongan Gus Miftah tu kayak sampah. Dia borong atau bahkan ngasih tu bapak2 ampe puluhan juta setelah itu juga ga mengubah mulut dia kayak sampah. Metode dakwah metode dakwah itu aja lah alasan kelen.', 'seaofhappinesss', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@K_aji_99 @Cyb3rOG1 caranya dakwah gus miftah seperti itu tetapi saat gus miftah ngrendahin kamu ikut tertawa ngakak Bib habib. Sok suci', 'nrmnah__', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@kurawa @Gerindra boycot gus satu itu! kalo bisa bikin petisi boycot gus miftah! biar presiden prabowo liat dan langsung di cabut jabatannya. emang nabi dlu nyontohin dakwah seperti itu? nge GOBLOK GOBLOKIN orang depan banyak orang bukan ciri khas atau suatu kebiasaan! tapi ADAB.', 'chelseathvv', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@tsrid_ @_mardial_ Ngangengngong fafifufufafa wasweswos sampeyan tuh gus juga islam itu haq dan bathil gada abu2. Bilang aja salah dn minta maaf gausa denial dgn tameng metode dakwah. Bullying efeknya ga maen2 dr ekspersi si bapak udah keliatan hatinya menangis koyak krn metode dakwah si miftah', 'BarkahAkba24352', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'jgn di maafin cancel aja lah si miftah dkk ini dah noyor2 istri org lg kerja di goblok2in di normalisasi pula gaya dakwah begitu wkwk gus gus gus noh gabung aja sm si agus', 'ngomongemengg2', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'dakwah mana ada yg gblk²in orang. CANCEL GUS MIFTAH', 'autumngalleaves', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@islah_bahrawi Gus Miftah Mau anda klarifikasi membenarkan diri setelah itu memborong semua dagangannya. Itu akan membuat kredibilitas anda turun sebanyak apapun kebaikan anda lebur karna kata katamu sendiri singkat tapi itu memalukan Islam. Terlebih anda sedang pada posisi dakwah.', '_terusann', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'dari dulu jg agak laen emang gus miftah itu inget dulu katanya pernah dakwah di gereja jg', '_sunmilky', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Hujandisenja Barisan sakit hati jagonya keok Wkwkwkw Dari dulu dakwah Gus Miftah kayak gitu sebelum nya', 'lompong82', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'gak masuk akal kalau dakwah dijadiin pembelaan buat melontarkan kalimat² semacam itu ke bapaknya Meskipun Gus Miftah mampu memborong dagangan² bukan berarti juga kalimat ''g*blok'' pantas dilontarkan ke pedagang. Pake bilang gk ada kapasitas dirimu aja ikutan ketawa di kejadian.', 'lalamoon55', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Ga peduli jg sih sebenernya gus miftah ngeborong semua dagangan bpknya apa engga tp masa dakwah yg model begitu dinormalisasi?', 'nafilahksj', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Gus miftah anj lah dakwah ngatain orang goblok. Sedih banget liat bapaknya yg jual es teb', 'bidadaritumbang', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, '3. Dagangannya dibeli kok di akhir kenapa gak dari awal aja dibeli terus ditutup dengan perkataan baik-baik doa-doa dan suri tauladan. Semoga jika masih ada kesempatan bapak kalian semua yang digoblok2in Gus Miftah dan kalian gaboleh marah karena itu berkah dakwah Miftah', 'kadalsantolo', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@neVerAl0nely INI GUS MIFTAH SIAPA SIH ANJ INGAT LU DI ACARA DAKWAH TOLOL BUKAN STAND UP KOMEDY ANJ', 'Iqbalplentong86', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Jadi kepo jaman nabi dulu dakwah beliau seperti apa ya.. Yang jelas gak kayak si gus miftah ini. Si zaidan juga sok sok an klarifikasi', 'blackyescor', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@inilahdotcom Coba dakwah di KARAWANG sudah di lempar batubata tuh si GUS MIFTAH modiiaarr', 'AsepMul48423805', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@islah_bahrawi Penjual es dia modal bro walau pendapatan sedikit tetapi berkah.. Lah miftah penjual agama modal ngapalin ayat modal dengerin kajian..gus baha tu d contoh kl dakwah.. Mulut pelonten ya ky miftah..', 'ElVino71533385', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, 'Masalah Gus Miftah punya niche dakwah sendiri dan berhasil di sana itu lain soal. Dia jadi panutan influencer tentu saya apresiasi benar. Tapi mendakwahkan hal-hal yang tidak sepenuhnya dia pahami apalagi terkait sisi yang sangat spiritual ini yang saya tidak bisa terima.', 'bienabbas', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Gw sbg org muslim benci bgt sama gus gus an macem miftah gini. Sok mengusung dakwah modern keliatannya aja toleransi tapi aslinya tai.', 'prkdlkntg', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@aissaputra__ Aku seko awal kurang sreg karo miftah mas. Seko cara dakwah guyonan dan lainnya agak kurang masuk dilontarkan oleh seorang yang katanya ''gus'' dan miftah cukup dikenal Arepo ilmune miftah duwur nek adab e nol to tetep wae kontol', 'bagaswarass__', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, 'Sejak ngikutin ngajinya Gus Miftah ibuku jadi normalisasi ngomong kasar bahkan ke anaknya. Gapapa ngomong kasar wong Gus Miftah aja bisa dakwah dengan cara itu https://t.co/wjYdG7M6kW', 'TanggapanH', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@3jandono @zy_zy_lestary Itu mah yg pernah di praktekkan gus miftah.. Dia kalo dakwah ke para purel dan psk dia dgn metode santun dan akrabin.. Jadi target dakwahnya dibikin nyaman dulu bukan tiba2 di ceramahin agama..', 'DewiPutriku06', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@UmarHasibuan__ Itu ngapain Gus Miftah ikut-ikutan politik !!! Mau aja dikibulin Jokowi', 'DakwahMedi91003', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'serakah banget bjir tuh juga kenapa deh gus miftah jadi menteri? mending balik dakwah aja nggak usah segala ikut politik. raffi juga nih uang dah banyak ngapain ikut politik???', 'jjonghaen', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (3, 'Gus Miftah wkwkw Memohon pertolongan kepada Allah agar dakwah sunnah ini tidak dibubarkan baser :)', 'awmeks', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@KemenperinRI padahal gus Miftah alasan ku jadi suka denger dakwah islami sekarang aku menyesal karena mendengar dakwah dakwah mending yang segenerasi aja kalo gini jadinya', 'SayuuuuNaru', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (3, 'Drdulu gasuka gus miftah krn dari caranya dakwah aja udah ga bgt sama kayak ga meyakinkan aja secara appearancenya', 'baeecedes', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@IchwanNur8 @PKSejahtera @hnurwahid mungkin pengen dakwah didalem wan. kayak gus miftah dakwah di diskotik tempat2 maksiat. kalo ga salah pks pernah jadi mentrinya SBY. internet maju swasembada padi. mungkin ini mau diulangi lagi. entah apa. abujanda tetep binatang piaraan.', 'KoweGebyangeten', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Setaraf ''cuman babi betina haram'' sok suci dakwah Gus Miftah kok jadi c(er)ita-ci(n)ta muslimin!!! https://t.co/jGPmldXqMQ', 'ru8ymarch', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Gus Miftah ngatain orang GOBLOK di bilang itu gak kasar dakwahnya memang begitu setiap kyai punya cara sendiri dalam berdakwah.', 'GanjaOto', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Piyusaja2 Belajar islam tu kayak sekolah lah.. Bagus banget kalau orang yg jauh sama Islam bisa kenal islam lewat Gus Miftah lalu naik lagi belajar ke habib jafar udah gitu harus naik kelas lagi belajar ke ust Adi Hidayat dst..', 'gitsunine', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'tempodotco minta maaf secara publik udah mundur Krn tdk tidak sanggup mengemban jabatan udah anda tidak hanya sebagai pendakwah anda juga seorang ksatria Gus bangsa ini musti bnyk belajar dri anda terutama pejabat publiknya. rispke Gus Miftah.. 5 jempol untuk anda', 'GemsBsc45364', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Para gus-gusan juga ini aduuuh kejadian sendiri di aku soalnya waktu adekku yang SMP ngomong kasar ibuku malah jawab gapapa ngomong kasar wong gus miftah aja dakwah juga ngomong kasar', 'TanggapanH', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (3, 'Setiap genre dakwah saya pikir baik. Ada Gus Iqdam Gus Muwafiq Gus Miftah Gus Baha Gus Ali Gondrong Kyai Anwar Zahid Habib Sech Ustadz Safiq dan Riza Basalamah UAH UAS dll. Yg penting tujuannya utk mendidik umat islam. Jangan saling mencela.', 'ToufikImtikhan2', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@thatxxgvrl @nurulalwi_ @kelulistarlight @tanyakanrl anak muda yg beneran cari ilmu buat dakwah tuh masih banyak contohnya Alwi Assegaf dipanggil Habib muda karena keturunan Rasulullah dan dia fokus memperdalam ilmu agamanya BUKAN JUAL AGAMA yg kedua ada Kadam Sidik disini dia termasuk Gus tapi juga fokus memperdalam ilmu agama.', 'blessfullyy', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (4, '@jessbrow_ @kelulistarlight @tanyakanrl Berarti ga cocok di elu ka cara dakwah dia Gua juga ikut kajian Hanan Ataki yg adem ayaem ga meresap kejiwa Jadi gua rasa gua butuh yg macem Abdul Somad/ Habib Riziq‍↕️ Beda2 kan kak emg cara penyampaiannya.. tp klo Gus yg kemarin ngatain gobs dan suka mesum beda ye', 'amzblb', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Hanya Muhammadiyah ormas yg tertata dengan baik secara ekonomi pendisikan sosial dakwah dan tidak ta''ashub gus gus...', 'AbyDens2', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@irfannuruddin_x @lilaccountz @pangbandrang Terimakasih sudah mewakili Gus temenku ada yg tak gituin juga. Konten dakwah mulu begitu ditanya ga bisa jawab tapi berani menyalahkan amalan orang lain. Jaaaannnn kudu tak hihhh...', 'nomadcircle', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@Samsullls @TukangBedah00 Dakwah aja cuma was wes wos coba debat sama UAH berani gak Gus mu Ngidam mu itu paling langsung mlengos lari tunggang langgang ciri khas penceramah jual agama tapi isinya tak berbobot klo UAH baru bener² penceramah sekaligus bagi ilmu demi kemaslahatan', 'perand_r', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@tanyarlfes Semua karna mereka semua memberikan dakwah menarik serta dengan bahasa yang baik tidak seperti sebelah yang pake gus gas gus tapi kelakuan kayak bengis', 'HanzSwell', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'Dan katanya metode dakwah. Woy laaah metode dakwah gak harus ngatain orang depan umum dan menertawakan yaaaa Lu juga siapa ya ? Ngebela habis habisan gus mu itu ! Padahal tinggal mengakui kalo salah ya salah bukan ngeles sana sini https://t.co/T1pOxzSm9H', 'critaharian', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (9, '@ekokuntadhi1 Gus apaan kocak. Mana ada gus bicaranya seperti beliau. Suka merendahkan orang lain bahas hal-hal dewasa saat dakwah. Mana ada. Beliau ini tidak pantas dipanggil gus ust dsb. Beliau ini seperti preman yang mabuk lagi berbicara agama. Sinting.', 'emfikrialfiansh', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@AirinDatangLagi Gus gusan kontol ngassuu... Ra bayaran yo moh ra gelem dakwah.... Mending dakwah bermutu... Isine selangkangan bacote kyok asu wkwkw', 'amoymoyom', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@PelatihT1dur NANGIS HILANG PAMOR HILANG JABATAN HILANG HARGA DIRI.. PERGI KE CLUB GUS.. CERAMABIN NOH PARA LONT3 LU KAN SUKA TUH DAKWAH DI CLUBING CLUBING... NGAKUNYA PRESIDEN PENDOSA TAPI CENGENG KAYAK BOCIL.. MULUT S4MPAH..', 'LangitLa3019', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@hipohan Pendak dakwah si bahasa nya ga patut di jaga. Gimana coba perasaan yg denger kajian dawah gus iqdam kan dia itu juga netizen yg bisa berkomentar di medsos juga', 'laury77585', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (2, '@SimbokeSarah @SangGuru2471 @FayaAtika @Simbok_Dharmi Lha mbok dakwah koyo ngono kui ditapuk lambene..gae gelar Gus ra ono turunan..gae gelar kyai tp lambene murang tata..Penceramah kok ra nyiarke welas asih lan tata laku seng bener...mundur umat ki nek penceramahe lawak', 'JoshGrobax', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@choisoobinl Kebanyakan ikut dakwah gus mif*tah ya gininih ngeselin anying []', 'urjiimin', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@fannanarch @ustadzsyafiq Udah pasti lah ulama2 Saudi menyampaikan. beliau kan di Indo di sini aja maksiat segala jenis ada. makanya dakwah di Indo itu berat muslimnya masih banyak yg menuhankan Gus &amp; habib habiban yg isi ceramahnya dongeng.. Makanya ga maju maju contoh di Jatim', 'keenan_reactive', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (365, '@ferizandra @msaid_didu Apalagi yg di undang gus gus di jawa timur ngajinya cuman guyon2 tok dgn alasan cara dakwah org beda beda yg penting sdh mau datang pengajian lha kan harusnya org udah datang di ajari ilmu agama bukan di ceritain lucu lucu dan di ajak nyanyi nyanyi', 'ilangit2', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Yogyakasta Sepakat banget sih kl mau dakwah lucu2an tinggalkan sebutan2 gus kyai dll mending sebut diri sbg komika malah lebih punya nilai tambah', 'pakharto25500', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@_lalalalice Ya ga dakwah juga dong mohon maaf bukan kayak yang gus gus an itu', 'Raablinkeuu1', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@copyraharja ini problemnya di attitude nya sih mas kalo guyonan mah monggo2 aja tp islam pny ajaran dalam beretika apalagi ketika menyampaikan dakwah. gus baha jg suka guyon tp penyampaiannya dengan baik tuh', 'nabiyeee', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (107, '@uuewew @Quvvatt Lahan dakwah umum juga hrs selaras dengan nash dan dalil (aqli dan naqli) bukan sembarang ngomong.. (sing penting ngguyu kuabeh). Maka hrs didukung niat dan upaya Gus Baha mengembalikan model kajian baik ilmu maupun dakwah.. Karena itu akan berbanding lurus dengan', 'Yogyakasta', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@ILCTalkshow Stop pake kata dakwah atau gus . Apapun namanya yg disampaikan sama orang itu dalam clip2 yg viral akhir2 ini bukan bagian dari Islam. Call him a sexist comedian making obnoxious porn related comments. Kami cukup ilmu kalau cuma untuk bedain mana yg dakwah mana yg ngeracau.', 'tobear333', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@ILCTalkshow Harusnya upgrade cara dakwah cari info siapa aja pendengarnya bukan malah dipukul rata dgn bahasa yg kasar dan guyonan yg saru. Ketika tau salah ya diingatkan bukan malah muter2 nyari pembenaran. Memang yg asli Gus ya Gus Baha'' dgn penampilan sederhana dan bahasa yg santun.', '__Kiyotaka', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@tanyarlfes Lagian emang dia dakwah? Ini mah gibah dia Gus tolol kesukaan rakyat sdm bodoh', 'Melioda23402804', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@jaeminunesa @mahaecoty_ @renjununesa dakwah dmn gus modelan kek gt', 'seunghanunesa', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'anjir lah ini yg dakwah di masjid pake toa deket rumah lg bahas si miftah mana pake belain si miftah... idie najong bat.. kek mana sih pemikirannya naudzubillah sesat ngebela gas gus segitunya kaya lagi bela nabi ih...', '_ilyeri', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@geloraco bukan ngurusi lonte emg doyan lonte aj orgnya cm ketutup framing dakwah gus munafik pantesmu', 'nnnightynight', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@Tan_Mar3M Pdhal dia terkenal ya krna netizen sm penyanyi2 dangdut. Bukan krna pinter dakwah nya. Belagu bgt mau jdi the next miftah nih gus gusan', 'bayu_mika', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@NyaiNeneng Dakwah di klub malam Gus berharap mampu merubah orang disana Ternyata orang disana yang merubah gus', 'ArdianSyah99967', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@Kanseulir Makanya klo dakwah pke dalil.. hadist ada.. sunnah ada.. riwayat imam ada.. Al quran ada.. trus npa bkin lawakan sndri.. tirulah lucunya gus dur.. penuh akhlak', 'AdolfWinn', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@VIVAcoid Dakwah cm mo cari ketawa doang jijik bgt gus gus an ini', 'rorcony', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, '@TukangBedah00 Dakwah itu pakai adab Cok.. jangan andalkan tarip dan nama Gus nya', 'BuihS77509', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'capek melihat drama gus gus an ini gus lain malah ngebela dan ngatain netizen gapernah ikut pengajian jd gatau situasi situasi apa emang membenarkan pake kata2 kasar? itu mah bukan dakwah tp ngebully : ))))) aneh betul lah orang2 ini', 'defallsforkyu', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'gus miftah emang bercandanya gitu daridulu INI BERCANDANYA??? INI??? NGELECEHIN ORANG DI DEPAN UMUM DI ACARA DAKWAH??????????', 'esekubse', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'YaAllah semoga para jawir jamaah gus gusan atau habib habiban ini cepat tersadarkan dari dakwah gak jelas seperti ini', 'maplespetal', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (1, '@Hilmi28 lebih tinggi derajatnya seorang stand up komedian sih... drpd yg ngaku ustad/gus/habib dgn guyonan jorok tp berbalut dakwah agama..', 'rezhend', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (78, '@lebihdariteman_ @VIVAcoid Entah lah org org goblok tuh nontonin tokoh agama yang kek gini dakwah apaan lu anjg puki presetan mau lu gus mau lu habib kelakuan kek setan tetap aja di mata gua setan https://t.co/YXRpzf2Ca0', 'jesuseaterz', 3);
INSERT INTO `Tweet` (`likes`, `content`, `username`, `category_id`) VALUES (0, 'ternyata banyak banget tingkah si gus M sama habib² itu yang kebongkar salah satu nya ini. malu²in banget mbk sadar kamu ini di lecehkan.. jijik banget dengerin nya ya Allah dakwah apaan begitu https://t.co/s7yqGHILep', 'cookiessysy', 3);

-- Select (Join & Subquery)
SELECT
  c.name AS kategori,
  COUNT(t.id) AS jumlah_tweet,
  (COUNT(t.id)/(SELECT COUNT(id) FROM Tweet) * 100) AS persentase
FROM Tweet AS t
JOIN Category AS c
ON t.category_id = c.id
GROUP BY category_id
ORDER BY jumlah_tweet;
